version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:5.7
        volumes:
             - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: app
            MYSQL_PORT_3306_TCP_ADDR: mysql
            MYSQL_PORT_3306_TCP_PORT: 3306
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8081:80'
